### ISSUE TITLE
reloadFileList request failed TypeError: Cannot read property '_fileList' of null

### ISSUE THREAD

**Issue by Sanjo** [Sanjo/meteor-karma#11]
reloadFileList request failed TypeError: Cannot read property '_fileList' of null

**Comment by luman75** [comment]
Hi we've got the same problem. It's only when we are running test with watching mode. 

This is example of the command we run

```
JASMINE_CLIENT_UNIT=$JASMINE_CLIENT_UNIT \
JASMINE_CLIENT_INTEGRATION=$JASMINE_CLIENT_INTEGRATION \
JASMINE_SERVER_INTEGRATION=$JASMINE_SERVER_INTEGRATION \
JASMINE_SERVER_UNIT=$JASMINE_SERVER_UNIT \
CUCUMBER=$CUCUMBER \
JASMINE_BROWSER=PhantomJS \
PHANTOMJS_BIN=/usr/local/bin/phantomjs \
SELENIUM_BROWSER=phantomjs \
JUNIT_DIRNAME=test-reports/ \
MONGO_URL=mongodb://$CHECK_MONGO.$CHECK_MONGO_IMAGENAME.$ROOT_URL_SUFFIX/app \
USERVICE_DISCOVERY_URL=mongodb://$CHECK_MONGO_CLUSTER.$CHECK_MONGO_CLUSTER_IMAGENAME.$ROOT_URL_SUFFIX/cluster \
USERVICE_NAME="$USERVICE_NAME" \
meteor $TESTS_ONCE
```


when ```$TESTS_ONCE = "--test"``` then  everything is fine. But when ```$TESTS_ONCE = ""``` (i.e. runs meteor in watching for changes  mode) then the we get  error

```
reloadFileList request failed TypeError: Cannot read property '_fileList' of null
```
and client unit tests doesn't work.

**Comment by Sanjo** [comment]
The hard fail should now be fixed with https://github.com/Sanjo/meteor-karma/commit/5c4e496955bbe17bc948d2b859065d45e7646e90. sanjo:karma@3.0.3
