### ISSUE TITLE
Karma sometimes fails to start

### ISSUE THREAD

**Issue by mortensteenrasmussen** [Sanjo/meteor-karma#14]
When running tests through our CI server, karma fails to start in around 10% of our builds. Its not consistent, and doesn't happen locally which leads me to believe this is a race condition.

The testing is started with `meteor --test`, and we're running sanjo-karma 3.1.0, and we're running with the following settings:
```
JASMINE_SERVER_UNIT=0
JASMINE_SERVER_INTEGRATION=1
JASMINE_CLIENT_UNIT=1
JASMINE_CLIENT_INTEGRATION=0
CUCUMBER=0
JASMINE_BROWSER=PhantomJS
VELOCITY_CI=1
VELOCITY_DEBUG=1
```

I'm seeing the following log when it fails, and it causes the build to hang forever (because the JASMINE_CLIENT_UNIT never finishes).
```
[12:30:02][Step 1/2] W20160126-08:28:23.308(0)? (STDERR) [sanjo:karma]: start request failed { [Error: connect ECONNREFUSED]
[12:30:02][Step 1/2] W20160126-08:28:23.309(0)? (STDERR)   code: 'ECONNREFUSED',
[12:30:02][Step 1/2] W20160126-08:28:23.309(0)? (STDERR)   errno: 'ECONNREFUSED',
[12:30:02][Step 1/2] W20160126-08:28:23.309(0)? (STDERR)   syscall: 'connect' }
```

Our build agents aren't the fastest in the world, which leads me to believe its a race condition. In the apiRequest, you have 5 retrys with 1000ms retryDelay. 

Is it possible to fix this issue or make the retry count and delay configurable? That way people with slow hardware can increase the retrycount or delay and not run into this.

When googling `[sanjo:karma]: start request failed { [Error: connect ECONNREFUSED]`, I can see other people have also experienced this.

**Comment by Sanjo** [comment]
Hi. I have just released 3.1.1. There is a chance that the version fixes your problem without any adjustments on the retry times. But I have also added environment variables for it: https://github.com/Sanjo/meteor-karma/commit/ec7673fd9c525a8678fe909fa26ff859c5a5b82a

**Comment by mortensteenrasmussen** [comment]
Thanks a bunch! I'm currently testing, and I'll close this issue within a few days unless I find something (specific).

Again, Thank you!

**Comment by JIoJIaJIu** [comment]
I have the same problem with 3.1.1 if I create only client unit tests
```
I20160331-17:00:36.601(3)? [velocity] Search framework for path tests/jasmine/client/unit/sample/src/Player.js
I20160331-17:00:36.602(3)? [velocity] Target framework for tests/jasmine/client/unit/sample/src/Player.js is jasmine-client-unit
I20160331-17:00:36.603(3)? [velocity] Search framework for path tests/jasmine/client/unit/sample/src/Song.js
I20160331-17:00:36.603(3)? [velocity] Target framework for tests/jasmine/client/unit/sample/src/Song.js is jasmine-client-unit
I20160331-17:00:36.604(3)? [velocity] Search framework for path tests/jasmine/client/unit/sample/spec/PlayerSpec.js
I20160331-17:00:36.605(3)? [velocity] Target framework for tests/jasmine/client/unit/sample/spec/PlayerSpec.js is jasmine-client-unit
I20160331-17:00:36.606(3)? [velocity] Search framework for path tests/jasmine/client/unit/sample/spec/SpecMatchers.js
I20160331-17:00:36.606(3)? [velocity] Target framework for tests/jasmine/client/unit/sample/spec/SpecMatchers.js is jasmine-client-unit
I20160331-17:00:36.606(3)? [velocity] File scan complete, now watching /tests
I20160331-17:00:36.606(3)? [velocity] Triggering queued startup functions
I20160331-17:00:36.655(3)? [sanjo:jasmine]: No tests for jasmine-server-integration found. Reporting completed.
I20160331-17:00:36.662(3)? [sanjo:jasmine]: No tests for jasmine-client-integration found. Reporting completed.
W20160331-17:00:40.729(3)? (STDERR) [sanjo:karma]: start request failed { [Error: connect ECONNREFUSED]
W20160331-17:00:40.729(3)? (STDERR)   code: 'ECONNREFUSED',
W20160331-17:00:40.730(3)? (STDERR)   errno: 'ECONNREFUSED',
W20160331-17:00:40.730(3)? (STDERR)   syscall: 'connect' }
```

**Comment by justingrayston** [comment]
Well, I am also @3.1.1 but this was all working fine until the Meteor 1.3 update. 

```
W20160331-21:30:22.551(1)? (STDERR) [sanjo:karma]: start request failed { [Error: connect ECONNREFUSED]
W20160331-21:30:22.552(1)? (STDERR)   code: 'ECONNREFUSED',
W20160331-21:30:22.552(1)? (STDERR)   errno: 'ECONNREFUSED',
W20160331-21:30:22.552(1)? (STDERR)   syscall: 'connect' }
```

In the server integration log I can see that there is dependency conflicts.

```
Errors prevented startup:
   
   While selecting package versions:
   error: Conflict: Constraint meteor@1.1.12 is not satisfied by meteor 1.1.10.
   Constraints on package "meteor":
   * meteor@=1.1.10 <- top level
   * meteor@1.1.7 <- meteor-base 1.0.1
   * meteor@1.1.7 <- underscore 1.0.4 <- accounts-base 1.2.2 <-
   accounts-facebook 1.0.6
```

@Sanjo is this because the Velocity mirror is actually running Meteor 1.2.1_2 not 1.3 and the Meteor 1.3 dependency versions conflict?

I guess this then may not be related to any of the above, or even the Karma start up because this error causes the start to fail anyway.

I guess as Velocity is effectively abandoned this may not get resolved as it has testing baked in now. However I don't really want to move from Jasmine to Mocha/Chai for all my tests. I guess I'll wait for that jasmine driver?

**Comment by mortensteenrasmussen** [comment]
Hi,

My bad for not closing this issue earlier. I believe the previous issue was resolved, and I would propose you create a new issue regarding the things you're seeing.

This is just to keep track of the different issues in the future. I will let this issue be open until you have created a new one.

Thanks in advance.

**Comment by justingrayston** [comment]
Hey, no problem.

I think you can close anyway as I think the issue is that the mirror is out of sync and that causes bad dependency conflicts preventing karma ever starting.

I have raised this on the velocity meteor reop https://github.com/meteor-velocity/meteor/issues/9

I don't know what is involved in the upgrade, happy to help there if I can.

**Comment by mortensteenrasmussen** [comment]
Thanks, closing this issue.
